import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarDemo } from "@/components/ui/navbar";
import { ThemeProvider } from "next-themes";
import { StickyBanner } from "@/components/ui/sticky-banner";
import FooterMobile from "@/components/footerMobile";

/* PRIMARY FONT — Monument Extended */
const monument = localFont({
  src: [
    {
      path: "./fonts/MonumentExtended-Regular.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-primary",
  display: "swap",
});

/* SECONDARY FONT — Poppins */
const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Catalyst Mar Baselios IEDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${monument.variable} ${poppins.variable} antialiased relative overflow-x-hidden`}
      >
        {/* GLOBAL SVG BACKGROUND */}
        <div
          className="fixed inset-0 -z-10 bg-no-repeat bg-cover bg-center opacity-40"
          style={{
            backgroundImage: "url('bg.svg')",
          }}
        />

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavbarDemo />

          <div className="relative">
            <StickyBanner className="bg-white">
              <p className="mx-auto max-w-[95%] text-center text-black drop-shadow-md">
                <span className="font-secondary font-bold">Relevent 2025</span>–
                Register Now – Gateway to Leadership and Innovation!
              </p>
            </StickyBanner>
          </div>

          {children}
          <FooterMobile />
        </ThemeProvider>
      </body>
    </html>
  );
}
